import React, { useState } from 'react';
import { Typography, TextField, Button, Avatar, Drawer, Grid, MenuItem, AppBar, Toolbar, IconButton, Badge, InputBase, Box } from '@mui/material';
import AddPhotoAlternateIcon from '@mui/icons-material/AddPhotoAlternate';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import Sidebar from './Sidebar';
import { Search as SearchIcon, Notifications as NotificationsIcon } from '@mui/icons-material';
import axios from "axios";
import { useNavigate } from 'react-router-dom'; // Importing useNavigate

function AddStudentPage() {
  const [cin, setCin] = useState('');
  const [numInscription, setNumInscription] = useState('');
  const [email, setEmail] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [address, setAddress] = useState('');
  const [photo, setPhoto] = useState(null);
  const [nom, setNom] = useState('');
  const [prenom, setPrenom] = useState('');
  const [password, setPassword] = useState('');
  const [dateNaissance, setDateNaissance] = useState('');
  const [groupe, setGroupe] = useState('');
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [successMessage, setSuccessMessage] = useState('');
  const navigate = useNavigate(); // Using useNavigate instead of useHistory

  const handleAddStudent = async () => {
    try {
      const response = await axios.post('http://localhost:9191/issatso/user/etudiant', {
        user: {
          nom,
          prenom,
          email,
          password,
          cin,
          date_nais: dateNaissance,
          numtel: phoneNumber,
          roles: 'ROLE_STUDENT' // Assuming you have roles defined
        },
        etudiant: {
          numInscri: numInscription, // This will be generated by the backend
          // Include other etudiant fields here
        }
      });
  
      if (response.status === 200) {
        setSuccessMessage('Étudiant ajouté avec succès');
        // Navigate to another page
        navigate('/studentspage');
      } else {
        throw new Error('Failed to add student');
      }
    } catch (error) {
      console.error('Error adding student:', error.message);
    }
  };
  
  const handlePhotoChange = (e) => {
    const file = e.target.files[0];
    const reader = new FileReader();
    reader.onloadend = () => {
      setPhoto(reader.result);
    };
    if (file) {
      reader.readAsDataURL(file);
    }
  };

  const handleGoBack = () => {
    window.history.back();
  };

  const handleSearchChange = (event) => {
    setSearchQuery(event.target.value);
  };

  return (
    <div style={{ display: 'flex' }}>
      <Drawer
        sx={{
          width: 240,
          flexShrink: 0,
          '& .MuiDrawer-paper': {
            width: 240,
            boxSizing: 'border-box',
          },
        }}
        variant="persistent"
        anchor="left"
        open={sidebarOpen}
      >
        <Sidebar />
      </Drawer>
      <div style={{ flexGrow: 1 }}>
        <AppBar position="static" sx={{ backgroundColor: '#3182CE' , marginTop:"-10px" , marginRight:"30px" }}>
          <Toolbar>
            <IconButton edge="start" color="inherit" onClick={handleGoBack}>
              <ArrowBackIcon />
            </IconButton>
            <Typography variant="h6" sx={{ flexGrow: 1 }}>
              Ajouter un étudiant
            </Typography>
            <Box sx={{ display: 'flex', alignItems: 'center' }}>
              <IconButton color="inherit">
                <SearchIcon />
              </IconButton>
              <InputBase
                placeholder="Rechercher..."
                inputProps={{ 'aria-label': 'search' }}
                value={searchQuery}
                onChange={handleSearchChange}
                sx={{ color: 'white' }} 
              />
              <IconButton color="inherit">
                <Badge badgeContent={4} color="secondary">
                  <NotificationsIcon />
                </Badge>
              </IconButton>
              <Avatar alt="Admin" src="/path/to/admin-image.jpg" sx={{ width: 40, height: 40, marginLeft: '8px' }} />
            </Box>
          </Toolbar>
        </AppBar>
        <Grid container spacing={2} style={{ padding: '20px', marginTop: '-10px', textAlign: 'center' }}>
        <Grid item xs={12}>
            <input
              type="file"
              accept="image/*"
              id="photo-input"
              style={{ display: 'none' }}
              onChange={handlePhotoChange}
            />
            <label htmlFor="photo-input">
              <Avatar
                alt="Photo de l'étudiant"
                src={photo}
                sx={{ width: 80, height: 80, cursor: 'pointer', margin: 'auto' }}
              >
                <AddPhotoAlternateIcon />
              </Avatar>
            </label>
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Nom"
              variant="outlined"
              size="small"
              value={nom}
              onChange={(e) => setNom(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Prénom"
              variant="outlined"
              size="small"
              value={prenom}
              onChange={(e) => setPrenom(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="CIN"
              variant="outlined"
              size="small"
              value={cin}
              onChange={(e) => setCin(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Numéro d'inscription"
              variant="outlined"
              size="small"
              value={numInscription}
              onChange={(e) => setNumInscription(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Email"
              variant="outlined"
              size="small"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Numéro de téléphone"
              variant="outlined"
              size="small"
              value={phoneNumber}
              onChange={(e) => setPhoneNumber(e.target.value)}
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              fullWidth
              label="Adresse"
              variant="outlined"
              size="small"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Mot de passe"
              variant="outlined"
              size="small"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </Grid>
          <Grid item xs={12} sm={6}>
            <TextField
              fullWidth
              label="Date de naissance"
              variant="outlined"
              size="small"
              type="date"
              value={dateNaissance}
              onChange={(e) => setDateNaissance(e.target.value)}
            />
          </Grid>
          <Grid item xs={12}>
            <TextField
              fullWidth
              select
              label="Groupe"
              variant="outlined"
              defaultValue=""
              size="small"
              value={groupe}
              onChange={(e) => setGroupe(e.target.value)}
            >
              <MenuItem value="groupe1"> 1</MenuItem>
              <MenuItem value="groupe2"> 2</MenuItem>
              <MenuItem value="groupe3"> 3</MenuItem>
              <MenuItem value="groupe3"> 4</MenuItem>
            </TextField>
          </Grid>
          <Grid item xs={12}>
            <Button
              variant="contained"
              color="primary"
              onClick={handleAddStudent}
            >
              Ajouter
            </Button>
          </Grid>
          {successMessage && (
            <Grid item xs={12}>
              <Typography variant="body1" color="success">
                {successMessage}
              </Typography>
            </Grid>
          )}
        </Grid>
      </div>
    </div>
  );
}

export default AddStudentPage;
